'use strict';

const https = require('https');

function post(hostname, path, headers, bodyStr) {
  return new Promise((resolve, reject) => {
    const req = https.request({
      hostname, path, method: 'POST',
      headers: { ...headers, 'Content-Length': Buffer.byteLength(bodyStr) }
    }, res => {
      let d = '';
      res.on('data', c => d += c);
      res.on('end', () => { try { resolve({ status: res.statusCode, body: JSON.parse(d) }); } catch { resolve({ status: res.statusCode, body: d }); } });
    });
    req.on('error', reject);
    req.write(bodyStr);
    req.end();
  });
}

exports.handler = async (event) => {
  if (event.httpMethod !== 'POST') return { statusCode: 405, body: 'Method Not Allowed' };

  const { email, reportHtml, date } = JSON.parse(event.body || '{}');
  if (!email || !reportHtml) return { statusCode: 400, body: JSON.stringify({ error: 'Missing email or report' }) };

  const resendKey = process.env.RESEND_API_KEY;
  if (!resendKey) {
    // No API key configured — return success anyway so UX isn't broken during setup
    console.log('RESEND_API_KEY not set — email not sent to:', email);
    return { statusCode: 200, body: JSON.stringify({ ok: true, demo: true }) };
  }

  const htmlBody = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <style>
    body { font-family: -apple-system, 'Inter', sans-serif; color: #111827; max-width: 680px; margin: 0 auto; padding: 2rem; font-size: 14px; line-height: 1.75; background: #faf8f5; }
    .header { border-bottom: 2px solid #05152e; padding-bottom: 1.25rem; margin-bottom: 2rem; }
    .brand { font-size: 1.3rem; color: #05152e; font-weight: 400; }
    .sub { font-size: .8rem; color: #6b7280; margin-top: .2rem; }
    .footer { border-top: 1px solid #e5e7eb; margin-top: 2rem; padding-top: 1rem; font-size: .75rem; color: #9ca3af; }
    a { color: #e07b6a; }
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">FunctionAgain Health</div>
    <div class="sub">Functional Blood Chemistry Analysis · ${date}</div>
  </div>
  ${reportHtml}
  <div class="footer">
    This report was generated by FunctionAgain Health's functional blood chemistry analysis tool. It is for educational purposes only and does not constitute medical advice. Always consult a licensed healthcare provider before making changes to your health regimen.<br/><br/>
    <a href="https://functionagain-health.netlify.app">functionagain-health.netlify.app</a>
  </div>
</body>
</html>`;

  const payload = JSON.stringify({
    from: 'FunctionAgain Health <reports@functionagain-health.netlify.app>',
    to: [email],
    subject: `Your Functional Health Report — ${date}`,
    html: htmlBody,
  });

  const result = await post('api.resend.com', '/emails', {
    'Authorization': `Bearer ${resendKey}`,
    'Content-Type': 'application/json',
  }, payload);

  if (result.status >= 200 && result.status < 300) {
    return { statusCode: 200, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ok: true }) };
  } else {
    console.error('Resend error:', result);
    return { statusCode: 500, body: JSON.stringify({ error: 'Email send failed' }) };
  }
};
